In [69]:
import pandas as pd
import numpy as np

In [70]:
df = pd.read_excel('outer join.xlsx')
df

,가맹점구분번호,기준년월,가맹점 운영개월수 구간,매출금액 구간,매출건수 구간,유니크 고객 수 구간,객단가 구간,취소율 구간,배달매출금액 비율,동일 업종 매출금액 비율,...,직장 이용 고객 비율,유동인구 이용 고객 비율,가맹점주소,가맹점명,브랜드구분코드,가맹점지역,업종,상권,개설일,폐업일
0,000F03E44A,202301,5.0,6.0,5.0,5.0,4.0,1.0,-999999.9,0.5,...,0.0,100.0,서울특별시 성동구 왕십리로4가길 9,육육**,NaN,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,NaN
1,000F03E44A,202302,5.0,6.0,6.0,6.0,6.0,NaN,-999999.9,0.0,...,-999999.9,-999999.9,서울특별시 성동구 왕십리로4가길 9,육육**,NaN,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,NaN
2,002816BA73,202404,2.0,3.0,4.0,4.0,2.0,6.0,-999999.9,96.6,...,23.8,52.4,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507.0,NaN
3,002816BA73,202411,2.0,3.0,4.0,4.0,2.0,6.0,-999999.9,108.0,...,11.5,76.9,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507.0,NaN
4,002816BA73,202406,2.0,4.0,4.0,4.0,2.0,1.0,-999999.9,74.2,...,17.4,69.6,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86896,29421280E6,202408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.2,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86897,7163461E10,202409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86898,5078575E67,202407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.8,68.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86899,8866726E15,202401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.1,44.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86900,42994169E6,202408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.1,66.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
#컬럼 순서 재배치
df[['가맹점구분번호', '기준년월', '가맹점주소',
       '가맹점명', '브랜드구분코드', '가맹점지역', '업종', '상권', '개설일', '폐업일', '가맹점 운영개월수 구간', '매출금액 구간', '매출건수 구간', '유니크 고객 수 구간',
       '객단가 구간', '취소율 구간', '배달매출금액 비율', '동일 업종 매출금액 비율', '동일 업종 매출건수 비율',
       '동일 업종 내 매출 순위 비율', '동일 상권 내 매출 순위 비율', '동일 업종 내 해지 가맹점 비중',
       '동일 상권 내 해지 가맹점 비중', '남성 20대이하 고객 비중', '남성 30대 고객 비중', '남성 40대 고객 비중',
       '남성 50대 고객 비중', '남성 60대이상 고객 비중', '여성 20대이하 고객 비중', '여성 30대 고객 비중',
       '여성 40대 고객 비중', '여성 50대 고객 비중', '여성 60대이상 고객 비중']]

,가맹점구분번호,기준년월,가맹점주소,가맹점명,브랜드구분코드,가맹점지역,업종,상권,개설일,폐업일,...,남성 20대이하 고객 비중,남성 30대 고객 비중,남성 40대 고객 비중,남성 50대 고객 비중,남성 60대이상 고객 비중,여성 20대이하 고객 비중,여성 30대 고객 비중,여성 40대 고객 비중,여성 50대 고객 비중,여성 60대이상 고객 비중
0,000F03E44A,202301,서울특별시 성동구 왕십리로4가길 9,육육**,NaN,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,100.0000,0.0000
1,000F03E44A,202302,서울특별시 성동구 왕십리로4가길 9,육육**,NaN,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,NaN,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,100.0000,0.0000
2,002816BA73,202404,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507.0,NaN,...,5.4384,23.6488,20.0232,22.8248,10.4648,1.1616,5.0512,4.2768,4.8752,2.2352
3,002816BA73,202411,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507.0,NaN,...,5.4855,18.9210,21.6240,20.5110,12.9585,1.4145,4.8790,5.5760,5.2890,3.3415
4,002816BA73,202406,서울 성동구 청계천로10나길 78,자갈***********,NaN,서울 성동구,요리주점,마장동,20140507.0,NaN,...,5.3760,22.8480,21.0840,23.9400,10.7520,1.0240,4.3520,4.0160,4.5600,2.0480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86896,29421280E6,202408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.1288,30.6708,13.9080,8.5644,3.0012,6.2712,11.2292,5.0920,3.1356,1.0988
86897,7163461E10,202409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.6192,18.7200,23.3376,9.8592,6.9264,2.1808,11.2800,14.0624,5.9408,4.1736
86898,5078575E67,202407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.4684,20.4684,2.2589,1.6135,1.2908,23.9316,23.9316,2.6411,1.8865,1.5092
86899,8866726E15,202401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.5676,18.8069,8.6765,8.3951,1.4539,10.8324,21.2931,9.8235,9.5049,1.6461
86900,42994169E6,202408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.3975,16.3195,19.8755,13.2715,8.5725,3.1025,9.3805,11.4245,7.6285,4.9275

In [81]:
#가맹점주소가 없는 행 삭제
#이유: 주소 등록이 안되어 있는 곳들
df = df.dropna(subset=['가맹점주소'])

In [82]:
df = df.fillna(-999999.9)

In [83]:
df

,가맹점구분번호,기준년월,가맹점 운영개월수 구간,매출금액 구간,매출건수 구간,유니크 고객 수 구간,객단가 구간,취소율 구간,배달매출금액 비율,동일 업종 매출금액 비율,...,직장 이용 고객 비율,유동인구 이용 고객 비율,가맹점주소,가맹점명,브랜드구분코드,가맹점지역,업종,상권,개설일,폐업일
0,000F03E44A,202301,5.0,6.0,5.0,5.0,4.0,1.0,-999999.9,0.5,...,0.0,100.0,서울특별시 성동구 왕십리로4가길 9,육육**,-999999.9,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,-999999.9
1,000F03E44A,202302,5.0,6.0,6.0,6.0,6.0,-999999.9,-999999.9,0.0,...,-999999.9,-999999.9,서울특별시 성동구 왕십리로4가길 9,육육**,-999999.9,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,-999999.9
2,002816BA73,202404,2.0,3.0,4.0,4.0,2.0,6.0,-999999.9,96.6,...,23.8,52.4,서울 성동구 청계천로10나길 78,자갈***********,-999999.9,서울 성동구,요리주점,마장동,20140507.0,-999999.9
3,002816BA73,202411,2.0,3.0,4.0,4.0,2.0,6.0,-999999.9,108.0,...,11.5,76.9,서울 성동구 청계천로10나길 78,자갈***********,-999999.9,서울 성동구,요리주점,마장동,20140507.0,-999999.9
4,002816BA73,202406,2.0,4.0,4.0,4.0,2.0,1.0,-999999.9,74.2,...,17.4,69.6,서울 성동구 청계천로10나길 78,자갈***********,-999999.9,서울 성동구,요리주점,마장동,20140507.0,-999999.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5.0,2.0,1.0,1.0,6.0,2.0,2.6,249.7,...,4.3,24.4,서울특별시 성동구 행당로5길 2,메가***********,커피전문점2,서울 성동구,커피전문점,-999999.9,20220823.0,-999999.9
86586,A7C2307794,202303,2.0,2.0,2.0,2.0,3.0,1.0,19.2,196.7,...,7.4,55.9,서울 성동구 한림말1길 8.,콩물*****,-999999.9,서울 성동구,한식-두부요리,옥수,20140508.0,-999999.9
86587,BF6A6456AB,202407,6.0,2.0,4.0,4.0,1.0,6.0,1.6,176.3,...,41.7,41.7,서울특별시 성동구 상원4길 11,우아**,-999999.9,서울 성동구,한식-육류/고기,뚝섬,20240131.0,20250724.0
86588,C59F032CAC,202406,1.0,2.0,2.0,2.0,4.0,2.0,24.0,116.5,...,11.3,48.7,서울 성동구 왕십리로 223-1,밸런***,샌드위치/토스트1,서울 성동구,샌드위치/토스트,한양대,20090421.0,-999999.9
86589,F46D45E328,202302,2.0,2.0,3.0,3.0,3.0,1.0,12.8,215.6,...,25.0,50.0,서울 성동구 용답중앙15길 13.,미*,-999999.9,서울 성동구,중식당,답십리,20131128.0,-999999.9

In [84]:
# 브랜드코드가 -999999.9인 행만 선택
mask = df['브랜드구분코드'] == -999999.9
missing_df = df[mask].copy()

# 1️⃣ 업종 + 가맹점명 조합으로 그룹 지정
missing_df['브랜드구분코드'] = (
    missing_df.groupby('업종')['가맹점명'].rank(method='dense').astype(int).astype(str)
)

# 2️⃣ 업종 이름 + 번호 붙이기
missing_df['브랜드구분코드'] = (
    missing_df['업종'] + missing_df['브랜드구분코드']
)

# 3️⃣ 원본에 반영
df.loc[mask, '브랜드구분코드'] = missing_df['브랜드구분코드']

In [85]:
df

,가맹점구분번호,기준년월,가맹점 운영개월수 구간,매출금액 구간,매출건수 구간,유니크 고객 수 구간,객단가 구간,취소율 구간,배달매출금액 비율,동일 업종 매출금액 비율,...,직장 이용 고객 비율,유동인구 이용 고객 비율,가맹점주소,가맹점명,브랜드구분코드,가맹점지역,업종,상권,개설일,폐업일
0,000F03E44A,202301,5.0,6.0,5.0,5.0,4.0,1.0,-999999.9,0.5,...,0.0,100.0,서울특별시 성동구 왕십리로4가길 9,육육**,중식-딤섬/중식만두1,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,-999999.9
1,000F03E44A,202302,5.0,6.0,6.0,6.0,6.0,-999999.9,-999999.9,0.0,...,-999999.9,-999999.9,서울특별시 성동구 왕십리로4가길 9,육육**,중식-딤섬/중식만두1,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,-999999.9
2,002816BA73,202404,2.0,3.0,4.0,4.0,2.0,6.0,-999999.9,96.6,...,23.8,52.4,서울 성동구 청계천로10나길 78,자갈***********,요리주점52,서울 성동구,요리주점,마장동,20140507.0,-999999.9
3,002816BA73,202411,2.0,3.0,4.0,4.0,2.0,6.0,-999999.9,108.0,...,11.5,76.9,서울 성동구 청계천로10나길 78,자갈***********,요리주점52,서울 성동구,요리주점,마장동,20140507.0,-999999.9
4,002816BA73,202406,2.0,4.0,4.0,4.0,2.0,1.0,-999999.9,74.2,...,17.4,69.6,서울 성동구 청계천로10나길 78,자갈***********,요리주점52,서울 성동구,요리주점,마장동,20140507.0,-999999.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5.0,2.0,1.0,1.0,6.0,2.0,2.6,249.7,...,4.3,24.4,서울특별시 성동구 행당로5길 2,메가***********,커피전문점2,서울 성동구,커피전문점,-999999.9,20220823.0,-999999.9
86586,A7C2307794,202303,2.0,2.0,2.0,2.0,3.0,1.0,19.2,196.7,...,7.4,55.9,서울 성동구 한림말1길 8.,콩물*****,한식-두부요리1,서울 성동구,한식-두부요리,옥수,20140508.0,-999999.9
86587,BF6A6456AB,202407,6.0,2.0,4.0,4.0,1.0,6.0,1.6,176.3,...,41.7,41.7,서울특별시 성동구 상원4길 11,우아**,한식-육류/고기250,서울 성동구,한식-육류/고기,뚝섬,20240131.0,20250724.0
86588,C59F032CAC,202406,1.0,2.0,2.0,2.0,4.0,2.0,24.0,116.5,...,11.3,48.7,서울 성동구 왕십리로 223-1,밸런***,샌드위치/토스트1,서울 성동구,샌드위치/토스트,한양대,20090421.0,-999999.9
86589,F46D45E328,202302,2.0,2.0,3.0,3.0,3.0,1.0,12.8,215.6,...,25.0,50.0,서울 성동구 용답중앙15길 13.,미*,중식당29,서울 성동구,중식당,답십리,20131128.0,-999999.9

In [ ]:
df.loc[
    (df['가맹점주소'] == '서울특별시 성동구 왕십리로4가길 9') &
    (df['가맹점명'] == '육육**'),
    '브랜드구분코드'
] = '중식'

In [87]:
# 숫자 부분 제거해서 브랜드명만 추출
df['브랜드이름'] = df['브랜드구분코드'].str.replace(r'\d+', '', regex=True)

# 브랜드이름별로 몇 가지 코드(숫자 버전)가 있는지 계산
brand_counts = df.groupby('브랜드이름')['브랜드구분코드'].nunique().sort_values(ascending=False)

brand_counts

브랜드이름
한식-육류/고기     366
백반/가정식       301
카페           289
한식-단품요리일반    279
축산물          239
            ...
탕후루            1
스테이크           1
주스             1
차              1
유제품            1
Name: 브랜드구분코드, Length: 73, dtype: int64

In [99]:
brand_counts.to_excel('브랜드이름별 개수.xlsx')

In [91]:
df.drop(columns = '브랜드이름')

,가맹점구분번호,기준년월,가맹점 운영개월수 구간,매출금액 구간,매출건수 구간,유니크 고객 수 구간,객단가 구간,취소율 구간,배달매출금액 비율,동일 업종 매출금액 비율,...,직장 이용 고객 비율,유동인구 이용 고객 비율,가맹점주소,가맹점명,브랜드구분코드,가맹점지역,업종,상권,개설일,폐업일
0,000F03E44A,202301,5.0,6.0,5.0,5.0,4.0,1.0,-999999.9,0.5,...,0.0,100.0,서울특별시 성동구 왕십리로4가길 9,육육**,중식-딤섬/중식만두1,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,-999999.9
1,000F03E44A,202302,5.0,6.0,6.0,6.0,6.0,-999999.9,-999999.9,0.0,...,-999999.9,-999999.9,서울특별시 성동구 왕십리로4가길 9,육육**,중식-딤섬/중식만두1,서울 성동구,중식-딤섬/중식만두,뚝섬,20220225.0,-999999.9
2,002816BA73,202404,2.0,3.0,4.0,4.0,2.0,6.0,-999999.9,96.6,...,23.8,52.4,서울 성동구 청계천로10나길 78,자갈***********,요리주점52,서울 성동구,요리주점,마장동,20140507.0,-999999.9
3,002816BA73,202411,2.0,3.0,4.0,4.0,2.0,6.0,-999999.9,108.0,...,11.5,76.9,서울 성동구 청계천로10나길 78,자갈***********,요리주점52,서울 성동구,요리주점,마장동,20140507.0,-999999.9
4,002816BA73,202406,2.0,4.0,4.0,4.0,2.0,1.0,-999999.9,74.2,...,17.4,69.6,서울 성동구 청계천로10나길 78,자갈***********,요리주점52,서울 성동구,요리주점,마장동,20140507.0,-999999.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86585,A2D9C941A9,202304,5.0,2.0,1.0,1.0,6.0,2.0,2.6,249.7,...,4.3,24.4,서울특별시 성동구 행당로5길 2,메가***********,커피전문점2,서울 성동구,커피전문점,-999999.9,20220823.0,-999999.9
86586,A7C2307794,202303,2.0,2.0,2.0,2.0,3.0,1.0,19.2,196.7,...,7.4,55.9,서울 성동구 한림말1길 8.,콩물*****,한식-두부요리1,서울 성동구,한식-두부요리,옥수,20140508.0,-999999.9
86587,BF6A6456AB,202407,6.0,2.0,4.0,4.0,1.0,6.0,1.6,176.3,...,41.7,41.7,서울특별시 성동구 상원4길 11,우아**,한식-육류/고기250,서울 성동구,한식-육류/고기,뚝섬,20240131.0,20250724.0
86588,C59F032CAC,202406,1.0,2.0,2.0,2.0,4.0,2.0,24.0,116.5,...,11.3,48.7,서울 성동구 왕십리로 223-1,밸런***,샌드위치/토스트1,서울 성동구,샌드위치/토스트,한양대,20090421.0,-999999.9
86589,F46D45E328,202302,2.0,2.0,3.0,3.0,3.0,1.0,12.8,215.6,...,25.0,50.0,서울 성동구 용답중앙15길 13.,미*,중식당29,서울 성동구,중식당,답십리,20131128.0,-999999.9

In [98]:
df['가맹점구분번호'].nunique()

4179

In [92]:
df.to_excel('브랜드구분코드 처리완료.xlsx')

In [103]:
df[df['브랜드구분코드']=='커피전문점54']

,가맹점구분번호,기준년월,가맹점 운영개월수 구간,매출금액 구간,매출건수 구간,유니크 고객 수 구간,객단가 구간,취소율 구간,배달매출금액 비율,동일 업종 매출금액 비율,...,유동인구 이용 고객 비율,가맹점주소,가맹점명,브랜드구분코드,가맹점지역,업종,상권,개설일,폐업일,브랜드이름
28082,D0C8ACE492,202411,6.0,6.0,5.0,5.0,6.0,1.0,-999999.9,1.7,...,85.7,서울특별시 성동구 천호대로 320,제이****************,커피전문점54,서울 성동구,커피전문점,답십리,20240920.0,-999999.9,커피전문점
51600,D0C8ACE492,202409,6.0,6.0,6.0,6.0,6.0,-999999.9,-999999.9,0.0,...,-999999.9,서울특별시 성동구 천호대로 320,제이****************,커피전문점54,서울 성동구,커피전문점,답십리,20240920.0,-999999.9,커피전문점
63678,D0C8ACE492,202410,6.0,6.0,5.0,5.0,6.0,1.0,-999999.9,1.0,...,87.5,서울특별시 성동구 천호대로 320,제이****************,커피전문점54,서울 성동구,커피전문점,답십리,20240920.0,-999999.9,커피전문점
66714,D0C8ACE492,202412,6.0,6.0,4.0,5.0,6.0,1.0,-999999.9,2.7,...,80.0,서울특별시 성동구 천호대로 320,제이****************,커피전문점54,서울 성동구,커피전문점,답십리,20240920.0,-999999.9,커피전문점